apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-configmap
  labels:
    app: telegraf-deployment
data:
  1-base.conf: |
    [global_tags]
    [agent]
      interval = "10s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      precision = ""
      hostname = ""
      omit_hostname = false
  2-inputs.conf: |
    [[inputs.nats]]
      server = "http://nats-clusterip:8222"
    [[inputs.influxdb_listener]]
      service_address = ":8186"
      read_timeout = "10s"
      write_timeout = "10s"
      max_body_size = 0
  3-outputs.conf: |
    [[outputs.influxdb]]
      urls = ["http://influxdb-clusterip:8086"]
      database = "telegraf"
