apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: sotah-api-
commonLabels:
  app: sotah-api
resources:
  - logs-pvc.yaml
  - nodeport.yaml
  - telegraf-sidecar-configmap.yaml
  - statefulset.yaml
