apiVersion: v1
kind: Service
metadata:
  name: nodeport
spec:
  type: NodePort
  selector:
    app: deployment
  ports:
    - protocol: TCP
      name: nodeport-private-ingress
      port: 8080
      targetPort: 8080
      nodePort: 30001
    - protocol: TCP
      name: nodeport-public-ingress
      port: 8081
      targetPort: 8081
      nodePort: 30002
