apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset
spec:
  selector:
    matchLabels:
      app: statefulset
  serviceName: nodeport
  replicas: 1
  template:
    spec:
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
        - name: gcr-json-key
      containers:
        - name: container
          image: "gcr.io/sotah-prod/api"
          resources:
            limits:
              cpu: "1000m"
              memory: "500Mi"
            requests:
              cpu: "500m"
              memory: "250Mi"
          command: ["npm", "start"]
          args: ["-s"]
          env:
            - name: PRIVATE_PORT
              value: "8080"
            - name: PUBLIC_PORT
              value: "8081"
            - name: CLIENT_HOST
              value: http://localhost:3000
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: ""
            - name: NATS_HOST
              value: nats-clusterip
            - name: NATS_PORT
              value: "4222"
            - name: DB_HOST
              value: postgresql-clusterip
            - name: LOGS_DIR
              value: /srv/app/logs
          ports:
            - containerPort: 8080
              name: private
            - containerPort: 8081
              name: public
          volumeMounts:
            - name: volume
              mountPath: /srv/app/logs
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: pvc
