apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-sidecar-configmap
data:
  1-base.conf: |
    [global_tags]
    [agent]
      interval = "10s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      precision = ""
      hostname = ""
      omit_hostname = false
  2-inputs.conf: |
    [[inputs.tail]]
      files = ["/srv/sotah-logs/current.log"]
      data_format = "logfmt"
  3-outputs.conf: |
    [[outputs.influxdb]]
      urls = ["http://telegraf-clusterip:8186"]
      database = "telegraf"
    [[outputs.file]]
      files = ["/var/log/metrics.out"]
      data_format = "influx"
