apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: deployment
  replicas: 1
  template:
    spec:
      containers:
        - name: containers
          image: nats:2.6-alpine
          resources:
            limits:
              cpu: "200m"
              memory: "500Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"
