apiVersion: apps/v1
kind: Deployment
metadata:
  name: sotah-server-prod-metrics-deployment
spec:
  selector:
    matchLabels:
      app: sotah-server-prod-metrics-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: sotah-server-prod-metrics-deployment
    spec:
      containers:
      - name: sotah-server-prod-metrics-container
        image: "gcr.io/sotah-prod/server"
        env:
        - name: PROJECT_ID
          value: sotah-prod
        command: [
          "/go/bin/app",
          "--cache-dir", "/tmp",
          "-v", "debug",
          "prod-metrics"
        ]
