apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sotah-server-prod-items-statefulset
spec:
  selector:
    matchLabels:
      app: sotah-server-prod-items-statefulset
  serviceName: sotah-server-prod-items-service
  replicas: 1
  template:
    metadata:
      labels:
        app: sotah-server-prod-items-statefulset
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: sotah-server-prod-items-container
        image: "gcr.io/sotah-prod/server"
        env:
          - name: PROJECT_ID
            value: sotah-prod
        command: [
          "/go/bin/app",
          "--cache-dir", "/srv",
          "-v", "debug",
          "prod-items"
        ]
        volumeMounts:
        - name: sotah-server-prod-items-data
          mountPath: /srv/items
      volumes:
      - name: sotah-server-prod-items-data
        persistentVolumeClaim:
          claimName: sotah-server-prod-items-pvc