apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sotah-server-prod-pricelist-histories-statefulset
spec:
  selector:
    matchLabels:
      app: sotah-server-prod-pricelist-histories-statefulset
  serviceName: sotah-server-prod-pricelist-histories-service
  replicas: 1
  template:
    metadata:
      labels:
        app: sotah-server-prod-pricelist-histories-statefulset
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: sotah-server-prod-pricelist-histories-container
        image: "gcr.io/sotah-prod/server"
        env:
          - name: PROJECT_ID
            value: sotah-prod
          - name: NATS_HOST
            valueFrom:
              configMapKeyRef:
                name: hostnames-configmap
                key: NATS_HOST
          - name: NATS_PORT
            valueFrom:
              configMapKeyRef:
                name: hostnames-configmap
                key: NATS_PORT
        command: [
          "/go/bin/app",
          "--cache-dir", "/srv",
          "-v", "debug",
          "prod-pricelist-histories"
        ]
        resources:
          requests:
            cpu: 300m
          limits:
            cpu: 750m
        volumeMounts:
        - name: sotah-server-prod-pricelist-histories-data
          mountPath: /srv/databases
      volumes:
      - name: sotah-server-prod-pricelist-histories-data
        persistentVolumeClaim:
          claimName: sotah-server-prod-pricelist-histories-pvc