apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
spec:
  selector:
    matchLabels:
      app: telegraf-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: telegraf-deployment
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: telegraf-container
          image: telegraf:1.20-alpine
          command: ["telegraf"]
          args: [
              "--config", "/srv/telegraf/1-base.conf",
              "--config-directory", "/srv/telegraf"
          ]
          volumeMounts:
            - name: telegraf-data
              mountPath: /srv/telegraf
      volumes:
        - name: telegraf-data
          configMap:
            name: telegraf-configmap
