apiVersion: batch/v1
kind: Job
metadata:
  name: statefulset
spec:
  template:
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Never
      imagePullSecrets:
        - name: gcr-json-key
      containers:
        - name: container
          image: "gcr.io/sotah-prod/server"
          resources:
            limits:
              cpu: "1000m"
              memory: "500Mi"
            requests:
              cpu: "500m"
              memory: "250Mi"
          command: ["/go/bin/app"]
          args: [
            "--is-local",
            "-c", "/srv/sotah-server/config.json",
            "--cache-dir", "/srv/sotah-server/data",
            "-v", "debug",
            "download-auctions"
          ]
          env:
            - name: NATS_HOST
              value: nats-clusterip
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: battlenet-creds
                  key: client-id
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: battlenet-creds
                  key: client-secret
            - name: INFLUXDB_LOG_HOST
              value: telegraf-clusterip
            - name: INFLUXDB_LOG_PORT
              value: "8186"
          volumeMounts:
            - name: volume
              mountPath: /srv/sotah-server
            - name: configmap
              mountPath: /srv/sotah-server/config.json
              subPath: config.json
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: pvc
        - name: configmap
          configMap:
            name: configmap
            items:
              - key: config.json
                path: config.json
  backoffLimit: 0
