apiVersion: v1
kind: Service
metadata:
  name: chronograf-nodeport
  labels:
    app: chronograf-nodeport
spec:
  type: NodePort
  selector:
    app: chronograf-statefulset
  ports:
    - protocol: TCP
      name: chronograf-nodeport-client-ingress
      port: 8888
      targetPort: 8888
