apiVersion: v1
kind: Service
metadata:
  name: telegraf-clusterip
  labels:
    app: telegraf-clusterip
spec:
  type: ClusterIP
  selector:
    app: telegraf-deployment
  ports:
    - protocol: TCP
      name: telegraf-clusterip-syslog-ingress
      port: 6514
      targetPort: 6514
