apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset
spec:
  selector:
    matchLabels:
      app: statefulset
  serviceName: clusterip
  replicas: 1
  template:
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: container
          image: influxdb:1.8-alpine
          resources:
            limits:
              cpu: "1000m"
              memory: "500Mi"
            requests:
              cpu: "500m"
              memory: "250Mi"
          ports:
            - containerPort: 8086
              name: ingress
          env:
            - name: INFLUXDB_DB
              value: telegraf
          volumeMounts:
            - name: volume
              mountPath: /var/lib/influxdb
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: pvc
