apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sotah-server-prod-live-auctions-pvc
spec:
  storageClassName: faster
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi