apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdb-statefulset
spec:
  selector:
    matchLabels:
      app: influxdb-statefulset
  serviceName: influxdb-clusterip
  replicas: 1
  template:
    metadata:
      labels:
        app: influxdb-statefulset
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: influxdb-container
          image: influxdb:1.8-alpine
          resources:
            limits:
              cpu: "1000m"
              memory: "500Mi"
            requests:
              cpu: "500m"
              memory: "250Mi"
          ports:
            - containerPort: 8086
              name: ingress
          env:
            - name: INFLUXDB_DB
              value: telegraf
          volumeMounts:
            - name: influxdb-volume
              mountPath: /var/lib/influxdb
      volumes:
        - name: influxdb-volume
          persistentVolumeClaim:
            claimName: influxdb-pvc
