apiVersion: v1
kind: Service
metadata:
  name: grafana-nodeport
  labels:
    app: grafana-nodeport
spec:
  type: NodePort
  selector:
    app: grafana-statefulset
  ports:
    - protocol: TCP
      name: grafana-nodeport-client-ingress
      port: 3000
      targetPort: 3000
