apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  labels:
    app: influxdb-service
spec:
  type: NodePort
  selector:
    app: influxdb-statefulset
  ports:
  - protocol: TCP
    name: ingress
    port: 8086
    targetPort: 8086