apiVersion: v1
kind: Service
metadata:
  name: nats
spec:
  type: ClusterIP
  selector:
    app: nats
  ports:
    - protocol: TCP
      name: client-ingress
      port: 4222
      targetPort: 4222
    - protocol: TCP
      name: service-ingress
      port: 8222
      targetPort: 8222