apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
spec:
  selector:
    matchLabels:
      app: telegraf-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: telegraf-deployment
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: telegraf-container
          image: telegraf:1.20-alpine
          volumeMounts:
            - name: telegraf-data
              mountPath: /etc/telegraf/telegraf.d
      volumes:
        - name: telegraf-data
          configMap:
            name: telegraf-configmap
