apiVersion: v1
kind: Service
metadata:
  name: clusterip
spec:
  type: ClusterIP
  selector:
    app: telegraf-deployment
  ports:
    - protocol: TCP
      name: telegraf-clusterip-influxdb-ingress
      port: 8186
      targetPort: 8186
