apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
spec:
  selector:
    matchLabels:
      app: postgres-statefulset
  serviceName: postgres-clusterip
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-statefulset
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: postgres-container
          image: "postgres:11"
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
            - name: PGDATA
              value: /var/lib/postgresql/data
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
