apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sotah-server-statefulset
spec:
  selector:
    matchLabels:
      app: sotah-server-statefulset
  serviceName: sotah-server-clusterip
  replicas: 1
  template:
    metadata:
      labels:
        app: sotah-server-statefulset
    spec:
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
        - name: gcr-json-key
      containers:
        - name: sotah-server-container
          image: "gcr.io/sotah-prod/server"
          resources:
            limits:
              cpu: "1000m"
              memory: "500Mi"
            requests:
              cpu: "500m"
              memory: "250Mi"
          command: ["/go/bin/app"]
          args: [
              "--is-local",
              "-c", "/srv/sotah-server/config.json",
              "--cache-dir", "/srv/sotah-server/data",
              "-v", "debug",
              "api"
          ]
          env:
            - name: NATS_HOST
              value: nats-clusterip
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: battlenet-creds
                  key: client-id
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: battlenet-creds
                  key: client-secret
            - name: LOGFILE
              value: /var/log/sotah-server.log
          volumeMounts:
            - name: sotah-server-volume
              mountPath: /srv/sotah-server
            - name: logs-volume
              mountPath: /var/log
        - name: telegraf-container
          image: telegraf:1.20-alpine
          command: ["telegraf"]
          args: [
              "--config", "/srv/telegraf/1-base.conf",
              "--config-directory", "/srv/telegraf"
          ]
          volumeMounts:
            - name: telegraf-sidecar-volume
              mountPath: /srv/telegraf
            - name: logs-volume
              mountPath: /srv/sotah-logs
      volumes:
        - name: sotah-server-volume
          persistentVolumeClaim:
            claimName: sotah-server-pvc
        - name: logs-volume
          persistentVolumeClaim:
            claimName: logs-pvc
        - name: telegraf-sidecar-volume
          configMap:
            name: telegraf-sidecar-configmap
