apiVersion: v1
kind: Service
metadata:
  name: clusterip
spec:
  type: ClusterIP
  selector:
    app: statefulset
  ports:
    - protocol: TCP
      name: ingress
      port: 5432
      targetPort: 5432
