apiVersion: v1
kind: Service
metadata:
  name: nodeport
spec:
  type: NodePort
  selector:
    app: deployment
  ports:
    - protocol: TCP
      name: nodeport-public-ingress
      port: 3000
      targetPort: 3000
      nodePort: 30000
