apiVersion: v1
kind: Service
metadata:
  name: clusterip
spec:
  type: ClusterIP
  selector:
    app: statefulset
  ports:
    - protocol: TCP
      name: clusterip-client-ingress
      port: 8086
      targetPort: 8086
