apiVersion: v1
kind: Service
metadata:
  name: nodeport
spec:
  type: NodePort
  selector:
    app: statefulset
  ports:
    - protocol: TCP
      name: nodeport-client-ingress
      port: 3000
      targetPort: 3000
      nodePort: 30003
