apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset
spec:
  selector:
    matchLabels:
      app: statefulset
  serviceName: nodeport
  replicas: 1
  template:
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsUser: 472
        fsGroup: 472
      containers:
        - name: container
          image: grafana/grafana:8.2.3
          ports:
            - containerPort: 3000
              name: ingress
          env:
            - name: GF_PATHS_DATA
              value: /srv/grafana/data
            - name: GF_PATHS_LOGS
              value: /srv/grafana/logs
            - name: GF_LOG_MODE
              value: console file
          volumeMounts:
            - name: volume
              mountPath: /srv/grafana
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: pvc
